### ISSUE TITLE
Idx out of range.

### ISSUE THREAD

**Issue by NOforgetQY** [charlesxu90/DeepSequence-torch#1]
Thank you very much for your contribution to this project！
#https://github.com/chloechsu/combining-evolutionary-and-assay-labelled-data/blob/main/src/vae_inference.py 
 ```
  focuscols = set(data_helper.uniprot_focus_cols_list)

    seqs = utils.read_fasta(os.path.join(WORKING_DIR, "datasets",
        args.fasta_file))
    wt, des = utils.read_fasta(args.wt_fasta_file, return_ids=True)
    wt = wt[0]
    des = des[0]
    offset = int(des.split('/')[-1].split('-')[0])
    delta_elbos = np.zeros(len(seqs))
    for i, s in enumerate(seqs):
        if i % 100 == 0:
            print(f'Computed elbos for {i} out of {len(seqs)} seqs')
            np.savetxt(os.path.join(args.output_dir, "elbo.npy"), delta_elbos)
        mut_tups = utils.seq2mutation_fromwt(s, wt, offset=offset)
        mut_tups = [t for t in mut_tups if t[0] in focuscols]
        delta_elbos[i] = data_helper.delta_elbo(vae_model, mut_tups,
                N_pred_iterations=N_ELBO_SAMPLES) 
    np.savetxt(os.path.join(args.output_dir, "elbo.npy"), delta_elbos)
```
I want to use the above code to get the corresponding `elbo.npy` file using the torch version of the trained model.
But I would get an error reported on this line of code, 
https://github.com/charlesxu90/DeepSequence-torch/blob/640db39769a93ef3d5bc11d6ad05aa7f5d761972/predictor.py#L33
and after checking it, I found that it was a problem with idx.
What should I do？
Best wish!
Thanks！

**Comment by charlesxu90** [comment]
I didn't tried to use this model with that fitness predictor benchmarking paper. This is out of the scope of this implementation.


You should show the all error lines. Otherwise, it's difficult to locate the real erratic lines. The line you quoted is simply obtaining the full sequence of mutations. Shouldn't cause such big problem.

The problem is most probabily coming from the integration part.
